import csv
import io
import os
import re
import textwrap
from typing import List, Dict
from urllib.parse import urlparse


def get_input_files(ucdm: List[Dict[str, str]], parameters: Dict[str, str]) -> Dict[str, str]:
    folder_path = os.path.dirname(os.path.abspath(__file__))
    return {
        "cohort.csv":      _build_cohort_csv(ucdm),
        "run_analysis.R":  _build_r_script(parameters),
        "main.nf":         _file_get_contents(os.path.join(folder_path, 'main.nf')),
        "nextflow.config": _file_get_contents(os.path.join(folder_path, 'nextflow.config')),
    }


def get_output_file_masks(parameters) -> Dict[str, str]:
    return {
        ".nextflow.log": ".nextflow.log",
        "report.html":   "report.html",
        "output/":       "output/",
    }


def get_nextflow_cmd(input_files: Dict[str, str], parameters, run_name: str, weblog_url: str) -> str:
    return (
        "sudo chown -R nextflow . ; "
        "nextflow run main.nf "
        "-name {name} "
        "-with-report report.html "
        "-with-weblog {weblog} "
        "-with-trace -ansi-log"
    ).format(name=run_name, weblog=weblog_url)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_cohort_csv(ucdm: List[Dict[str, str]]) -> str:
    """Convert UCDM rows to the standard OMOP cohort CSV."""
    buf = io.StringIO()
    writer = csv.DictWriter(
        buf,
        fieldnames=['cohort_definition_id', 'subject_id', 'cohort_start_date', 'cohort_end_date'],
    )
    writer.writeheader()
    for row in ucdm:
        writer.writerow({
            'cohort_definition_id': '1',
            'subject_id':           row['participant_id'],
            'cohort_start_date':    row.get('cohort_start_date', '2000-01-01'),
            'cohort_end_date':      row.get('cohort_end_date',   '2001-01-01'),
        })
    return buf.getvalue()


def _parse_dsn(dsn: str) -> dict:
    """
    Parse a SQLAlchemy DSN (e.g. postgresql+psycopg2://user:pass@host:5432/db)
    into the components expected by R DatabaseConnector.
    """
    # Strip dialect suffix: postgresql+psycopg2 -> postgresql
    dsn_clean = re.sub(r'\+[^:]+://', '://', dsn)
    parsed = urlparse(dsn_clean)

    dbms_map = {
        'postgresql': 'postgresql',
        'postgres':   'postgresql',
        'sqlite':     'sqlite',
    }
    return {
        'dbms':     dbms_map.get(parsed.scheme.lower(), parsed.scheme.lower()),
        'host':     parsed.hostname or 'localhost',
        'port':     str(parsed.port or 5432),
        'database': parsed.path.lstrip('/'),
        'user':     parsed.username or '',
        'password': parsed.password or '',
    }


def _r_int_vector(csv_str: str) -> str:
    """Convert comma-separated string of IDs to R integer vector, e.g. c(1L, 2L)."""
    ids = [x.strip() for x in csv_str.split(',') if x.strip()]
    if not ids:
        return 'integer(0)'
    return 'c(' + ', '.join(s + 'L' for s in ids) + ')'


def _build_r_script(parameters: Dict[str, str]) -> str:
    conn = _parse_dsn(parameters.get('dsn', ''))

    cdm_schema    = parameters.get('cdm_schema',    'public')
    work_schema   = parameters.get('work_schema',   cdm_schema)
    database_id   = parameters.get('database_id',   'local')
    target_ids    = _r_int_vector(parameters.get('target_ids',  '1'))
    outcome_ids   = _r_int_vector(parameters.get('outcome_ids', ''))
    min_cell_count = int(parameters.get('min_cell_count', 0))
    threads        = int(parameters.get('threads', 1))

    has_outcomes = parameters.get('outcome_ids', '').strip() != ''

    outcome_settings_block = ''
    if has_outcomes:
        outcome_settings_block = textwrap.dedent("""\
            settings$timeToEventSettings <- list(
                Characterization::createTimeToEventSettings(
                    targetIds  = targetIds,
                    outcomeIds = outcomeIds
                )
            )
            settings$dechallengeRechallengeSettings <- list(
                Characterization::createDechallengeRechallengeSettings(
                    targetIds  = targetIds,
                    outcomeIds = outcomeIds
                )
            )
            settings$riskFactorSettings <- list(
                Characterization::createRiskFactorSettings(
                    targetIds  = targetIds,
                    outcomeIds = outcomeIds
                )
            )
            settings$caseSeriesSettings <- list(
                Characterization::createCaseSeriesSettings(
                    targetIds  = targetIds,
                    outcomeIds = outcomeIds
                )
            )
        """)

    script = textwrap.dedent("""\
        # Auto-generated by Unison Runner – do not edit manually.

        Sys.setenv(LD_LIBRARY_PATH = paste0(
            "/usr/lib/jvm/java-21-openjdk-amd64/lib/server:",
            Sys.getenv("LD_LIBRARY_PATH")
        ))

        suppressPackageStartupMessages({{
            library(DatabaseConnector)
            library(Characterization)
        }})

        # ── Connection ────────────────────────────────────────────────────────
        connectionDetails <- DatabaseConnector::createConnectionDetails(
            dbms         = "{dbms}",
            server       = "{host}/{database}",
            user         = "{user}",
            password     = "{password}",
            port         = {port},
            pathToDriver = "/jdbc"
        )

        cdmDatabaseSchema  <- "{cdm_schema}"
        workDatabaseSchema <- "{work_schema}"
        cohortTable        <- "char_input_cohort"
        outputDir          <- "output"
        databaseId         <- "{database_id}"

        targetIds  <- {target_ids}
        outcomeIds <- {outcome_ids}

        # ── Load cohort from CSV ──────────────────────────────────────────────
        cohort_data <- read.csv("cohort.csv", stringsAsFactors = FALSE)
        cohort_data$cohort_definition_id <- as.integer(cohort_data$cohort_definition_id)
        cohort_data$subject_id           <- as.integer(cohort_data$subject_id)
        cohort_data$cohort_start_date    <- as.Date(cohort_data$cohort_start_date)
        cohort_data$cohort_end_date      <- as.Date(cohort_data$cohort_end_date)

        conn <- DatabaseConnector::connect(connectionDetails)

        DatabaseConnector::executeSql(conn, paste0(
            "DROP TABLE IF EXISTS {work_schema}.", cohortTable
        ))
        DatabaseConnector::executeSql(conn, paste0(
            "CREATE TABLE {work_schema}.", cohortTable, " (",
            "  cohort_definition_id BIGINT,",
            "  subject_id           BIGINT,",
            "  cohort_start_date    DATE,",
            "  cohort_end_date      DATE",
            ")"
        ))
        DatabaseConnector::insertTable(
            connection     = conn,
            databaseSchema = workDatabaseSchema,
            tableName      = cohortTable,
            data           = cohort_data,
            createTable    = FALSE
        )
        DatabaseConnector::disconnect(conn)

        # ── Characterization settings ─────────────────────────────────────────
        settings <- list()

        # Only use tables that exist in this CDM schema.
        # Era tables (condition_era, drug_era), device_exposure are excluded.
        covariateSettings <- FeatureExtraction::createCovariateSettings(
            useDemographicsGender                   = TRUE,
            useDemographicsAge                      = TRUE,
            useDemographicsAgeGroup                 = TRUE,
            useDemographicsRace                     = TRUE,
            useDemographicsEthnicity                = TRUE,
            useDemographicsIndexYear                = TRUE,
            useDemographicsIndexMonth               = TRUE,
            useDemographicsPriorObservationTime     = TRUE,
            useDemographicsPostObservationTime      = TRUE,
            useDemographicsTimeInCohort             = TRUE,
            useConditionOccurrenceAnyTimePrior      = TRUE,
            useConditionOccurrenceLongTerm          = TRUE,
            useConditionOccurrenceShortTerm         = TRUE,
            useDrugExposureAnyTimePrior             = TRUE,
            useDrugExposureLongTerm                 = TRUE,
            useDrugExposureShortTerm                = TRUE,
            useProcedureOccurrenceAnyTimePrior      = TRUE,
            useProcedureOccurrenceLongTerm          = TRUE,
            useProcedureOccurrenceShortTerm         = TRUE,
            useMeasurementAnyTimePrior              = TRUE,
            useMeasurementLongTerm                  = TRUE,
            useMeasurementShortTerm                 = TRUE,
            useObservationAnyTimePrior              = TRUE,
            useObservationLongTerm                  = TRUE,
            useObservationShortTerm                 = TRUE,
            useVisitCountLongTerm                   = TRUE,
            useVisitCountShortTerm                  = TRUE,
            useConditionEraAnyTimePrior             = FALSE,
            useConditionEraLongTerm                 = FALSE,
            useConditionEraShortTerm                = FALSE,
            useConditionEraOverlapping              = FALSE,
            useConditionGroupEraAnyTimePrior        = FALSE,
            useConditionGroupEraLongTerm            = FALSE,
            useConditionGroupEraShortTerm           = FALSE,
            useConditionGroupEraOverlapping         = FALSE,
            useDrugEraAnyTimePrior                  = FALSE,
            useDrugEraLongTerm                      = FALSE,
            useDrugEraShortTerm                     = FALSE,
            useDrugEraOverlapping                   = FALSE,
            useDrugGroupEraAnyTimePrior             = FALSE,
            useDrugGroupEraLongTerm                 = FALSE,
            useDrugGroupEraShortTerm                = FALSE,
            useDrugGroupEraOverlapping              = FALSE,
            useDeviceExposureAnyTimePrior           = FALSE,
            useDeviceExposureLongTerm               = FALSE,
            useDeviceExposureShortTerm              = FALSE
        )

        settings$targetBaselineSettings <- list(
            Characterization::createTargetBaselineSettings(
                targetIds           = targetIds,
                minPriorObservation = 0,
                covariateSettings   = covariateSettings
            )
        )

        {outcome_settings}
        charSettings <- do.call(Characterization::createCharacterizationSettings, settings)

        # ── Run analysis ──────────────────────────────────────────────────────
        dir.create(outputDir, recursive = TRUE, showWarnings = FALSE)

        Characterization::runCharacterizationAnalyses(
            connectionDetails        = connectionDetails,
            targetDatabaseSchema     = workDatabaseSchema,
            targetTable              = cohortTable,
            outcomeDatabaseSchema    = workDatabaseSchema,
            outcomeTable             = cohortTable,
            cdmDatabaseSchema        = cdmDatabaseSchema,
            characterizationSettings = charSettings,
            outputDirectory          = outputDir,
            databaseId               = databaseId,
            minCellCount             = {min_cell_count}L,
            threads                  = {threads}L,
            incremental              = TRUE
        )

        # ── Cleanup temp table ────────────────────────────────────────────────
        tryCatch({{
            conn2 <- DatabaseConnector::connect(connectionDetails)
            DatabaseConnector::executeSql(conn2, paste0(
                "DROP TABLE IF EXISTS {work_schema}.", cohortTable
            ))
            DatabaseConnector::disconnect(conn2)
        }}, error = function(e) message("Cleanup warning: ", e$message))

        message("Characterization complete. Results in: ", normalizePath(outputDir))
    """).format(
        dbms=conn['dbms'],
        host=conn['host'],
        database=conn['database'],
        user=conn['user'],
        password=conn['password'],
        port=conn['port'],
        cdm_schema=cdm_schema,
        work_schema=work_schema,
        database_id=database_id,
        target_ids=target_ids,
        outcome_ids=outcome_ids,
        outcome_settings=outcome_settings_block,
        min_cell_count=min_cell_count,
        threads=threads,
    )
    return script


def _file_get_contents(path: str) -> str:
    with open(path, 'r') as fh:
        return fh.read()
